# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name': 'Laptops', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterField(
            model_name='laptops',
            name='model',
            field=models.TextField(max_length=20, verbose_name='Model'),
        ),
    ]
