# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_auto_20201008_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='Laptop_Description',
            field=models.TextField(default='No Value', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptops',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Model'),
        ),
    ]
