# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0003_auto_20201008_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='Laptop_Description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
