# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0004_auto_20201008_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Laptop ID'),
        ),
    ]
