# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_auto_20201008_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_asset_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Assets.Laptops', verbose_name='Asset ')),
            ],
        ),
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Personal ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='First name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telphone', models.IntegerField(verbose_name='Telephone')),
                ('Department', models.CharField(max_length=30, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Assets.Personals', verbose_name='Owner ID'),
        ),
    ]
