# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0006_auto_20201008_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='personals',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photo/', verbose_name='Images'),
        ),
    ]
