# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0007_personals_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personals',
            options={'verbose_name': 'Personals', 'verbose_name_plural': 'Personals'},
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_asset_2',
            field=models.ForeignKey(default='no value', on_delete=django.db.models.deletion.PROTECT, related_name='Asset2', to='Assets.Laptops', verbose_name='Asset 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_asset_3',
            field=models.ForeignKey(default='no value', on_delete=django.db.models.deletion.PROTECT, related_name='Asset3', to='Assets.Laptops', verbose_name='Asset 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_asset_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Asset1', to='Assets.Laptops', verbose_name='Asset 1'),
        ),
    ]
