# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0009_auto_20201008_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='owner',
            name='Personal_id',
            field=models.ForeignKey(default='value', on_delete=django.db.models.deletion.PROTECT, to='Assets.Personals', verbose_name='Personal ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
