# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0011_auto_20201008_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personals',
            name='Department',
            field=models.CharField(max_length=30, null=True, verbose_name='Department'),
        ),
    ]
