# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0012_auto_20201008_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_asset_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Asset1', to='Assets.Laptops', verbose_name='Asset 1'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_asset_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Asset2', to='Assets.Laptops', verbose_name='Asset 2'),
        ),
        migrations.AlterField(
            model_name='personals',
            name='Department',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='personals',
            name='photo',
            field=models.ImageField(blank=True, default='nule', upload_to='user_photo/', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
