# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0013_auto_20201008_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_asset_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Asset1', to='Assets.Laptops', verbose_name='Asset 1'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_asset_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Asset2', to='Assets.Laptops', verbose_name='Asset 2'),
        ),
    ]
