# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0014_auto_20201008_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='Laptop_status',
            field=models.IntegerField(choices=[(1, '\u0644\u067e \u062a\u0627\u067e \u062f\u0631 \u0627\u0646\u0628\u0627\u0631'), (2, '\u0644\u067e \u062a\u0627\u067e \u0646\u0632\u062f \u06a9\u0627\u0631\u0628\u0631'), (3, '\u0644\u067e \u062a\u0627\u067e \u062f\u0631 \u062a\u0639\u0645\u06cc\u0631\u06af\u0627\u0647'), (4, ' \u0627\u0633\u0642\u0627\u0637 \u0634\u062f\u0647 \u0627\u0633\u062a')], verbose_name='Laptop Status'),
        ),
        migrations.AlterField(
            model_name='personals',
            name='photo',
            field=models.ImageField(blank=True, upload_to='staff_photo/', verbose_name='Images'),
        ),
    ]
