# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0015_auto_20201013_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='laptop_check_labled',
            field=models.BooleanField(default=False, verbose_name='Labled'),
        ),
    ]
